version: "3.8"

services:
  db:
    # M1mac用の環境
    #platform: linux/amd64
    container_name: 'db'
    build: ./db
    # settings.pyと設定を合わせる   
    environment:                 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    # sqlproに接続するためのポート設定（本番では開けない事）
    ports:
      - "4306:3306"
    volumes:
      - ./db/mysql_data:/var/lib/mysql

  web:
    container_name: 'web_go'
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    tty: true
    stdin_open: true
    volumes:
      - .:/go/src/app
    ports:
      - 8888:8888
    depends_on:
      - db